services:
  - type: web
    name: phishsleuth
    env: python
    buildCommand: |
      cd phishsleuth_backend
      pip install -r ../requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: |
      cd phishsleuth_backend
      gunicorn phishsleuth_backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: phishsleuth_backend.settings
      - key: SECRET_KEY
        value: your-strong-secret-key
      - key: DEBUG
        value: False
