services:
  - type: web
    name: phishsleuth-backend
    env: python
    region: Kenya
    plan: free # or starter/standard/pro based on your needs
    
    # Build configuration
    buildCommand: "./build.sh"
    
    # Start command - navigate to Django project and run gunicorn
    startCommand: "cd phishsleuth_backend && python -m gunicorn phishsleuth_backend.wsgi:application --bind 0.0.0.0:$PORT"
    
    # Environment variables
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 # specify your Python version
      - key: DJANGO_SETTINGS_MODULE
        value: phishsleuth_backend.settings
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*" # Update this to your domain in production
      - key: SECRET_KEY
        generateValue: true # Render will generate a secure secret key
      - key: DATABASE_URL
        fromDatabase:
          name: phishsleuth-db
          property: connectionString
    
    # Health check endpoint (optional)
    healthCheckPath: /health/ # Add this endpoint to your Django app if needed
    
    # Disk storage (if you need persistent storage)
    disk:
      name: phishsleuth-disk
      mountPath: /opt/render/project/src/phishsleuth_backend/media
      sizeGB: 1

# Database configuration (PostgreSQL recommended for production)
databases:
  - name: phishsleuth-db
    databaseName: phishsleuth
    user: phishsleuth_user
    plan: free # or starter/standard/pro
    region: oregon # should match your web service region
    ipAllowList: [] # empty means allow all IPs (adjust for security)

# Static site for frontend (if you have a separate frontend)
# - type: static
#   name: phishsleuth-frontend
#   env: static
#   buildCommand: npm run build
#   staticPublishPath: ./build
#   routes:
#     - type: rewrite
#       source: /*
#       destination: /index.html
