# Generated by Django 5.2.4 on 2025-07-13 18:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_scans', models.IntegerField(default=0)),
                ('threats_blocked', models.IntegerField(default=0)),
                ('false_positives', models.IntegerField(default=0)),
                ('processing_time_avg', models.FloatField(default=0.0)),
                ('accuracy_rate', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SuspiciousDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('domain_type', models.CharField(choices=[('shortener', 'URL Shortener'), ('spoofed', 'Spoofed Domain'), ('malicious', 'Known Malicious'), ('suspicious', 'Suspicious Pattern')], max_length=20)),
                ('risk_score', models.FloatField(default=0.5)),
                ('is_active', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-risk_score', 'domain'],
            },
        ),
        migrations.CreateModel(
            name='ThreatPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pattern', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('urgency', 'Urgency Indicators'), ('financial', 'Financial Terms'), ('social', 'Social Engineering'), ('technical', 'Technical Threats'), ('impersonation', 'Impersonation')], max_length=20)),
                ('weight', models.FloatField(default=1.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
                'unique_together': {('name', 'pattern')},
            },
        ),
        migrations.CreateModel(
            name='UserAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('rate_limit', models.IntegerField(default=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_key', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThreatAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('text', 'Text/Email Content'), ('url', 'URL Analysis'), ('file', 'File Upload')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('threat_score', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('threat_level', models.CharField(blank=True, choices=[('safe', 'Safe'), ('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], max_length=20)),
                ('is_phishing', models.BooleanField(default=False)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('ai_model_used', models.CharField(blank=True, max_length=100)),
                ('risk_factors', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('detected_threats', models.JSONField(blank=True, default=list)),
                ('highlighted_content', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threat_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='scanner_thr_user_id_6a81d8_idx'), models.Index(fields=['threat_level', '-created_at'], name='scanner_thr_threat__c660d6_idx'), models.Index(fields=['content_type', '-created_at'], name='scanner_thr_content_a917b0_idx')],
            },
        ),
    ]
